# ============================================================
# LEARNED PREFERENCE SCORING
# STEP 14
#
# Consumes learned preferences generated by
# the Feedback Agent.
#
# IMPORTANT:
# This does not replace:
#
# - Long-term preferences
# - Short-term preferences
#
# It adds a separate feedback-based score.
# ============================================================


# ============================================================
# STRENGTH WEIGHTS
# ============================================================


STRENGTH_WEIGHTS = {

    "weak": 1,

    "medium": 2,

    "strong": 3
}


# ============================================================
# NORMALIZE TEXT
# ============================================================


def normalize_text(
    value
):

    if value is None:

        return None

    return str(
        value
    ).lower().strip()


# ============================================================
# GET ITEM VALUES
# ============================================================


def get_item_values(
    item,
    attribute_group
):

    if attribute_group == "styles":

        return {

            normalize_text(
                value
            )

            for value in item.get(
                "style",
                []
            )

            if normalize_text(
                value
            )
        }


    if attribute_group == "colors":

        color = normalize_text(
            item.get("color")
        )

        return (
            {color}
            if color
            else set()
        )


    if attribute_group == "fits":

        fit = normalize_text(
            item.get("fit")
        )

        return (
            {fit}
            if fit
            else set()
        )


    if attribute_group == "categories":

        category = normalize_text(
            item.get("category")
        )

        return (
            {category}
            if category
            else set()
        )


    if attribute_group == "occasions":

        return {

            normalize_text(
                value
            )

            for value in item.get(
                "occasion",
                []
            )

            if normalize_text(
                value
            )
        }


    return set()


# ============================================================
# CALCULATE LEARNED PREFERENCE SCORE
# ============================================================
#
# Score range:
#
# 0 to 100
#
# Positive learned preferences add points.
# Avoided learned preferences reduce points.
# ============================================================


def calculate_learned_preference_score(
    outfit,
    learned_preferences
):

    if not learned_preferences:

        return 50.0


    items = outfit.get(
        "items",
        []
    )


    if not items:

        return 0.0


    preferred = learned_preferences.get(
        "preferred",
        {}
    )

    avoid = learned_preferences.get(
        "avoid",
        {}
    )


    positive_points = 0

    negative_points = 0

    maximum_points = 0


    # ========================================================
    # PREFERRED SIGNALS
    # ========================================================

    for attribute_group, preferences in (
        preferred.items()
    ):

        for preference in preferences:

            value = normalize_text(
                preference.get("value")
            )

            strength = preference.get(
                "strength",
                "weak"
            )

            weight = STRENGTH_WEIGHTS.get(
                strength,
                1
            )

            if not value:
                continue


            maximum_points += weight


            matched = any(

                value in get_item_values(

                    item,

                    attribute_group
                )

                for item in items
            )


            if matched:

                positive_points += weight


    # ========================================================
    # AVOIDED SIGNALS
    # ========================================================

    for attribute_group, preferences in (
        avoid.items()
    ):

        for preference in preferences:

            value = normalize_text(
                preference.get("value")
            )

            strength = preference.get(
                "strength",
                "weak"
            )

            weight = STRENGTH_WEIGHTS.get(
                strength,
                1
            )

            if not value:
                continue


            maximum_points += weight


            matched = any(

                value in get_item_values(

                    item,

                    attribute_group
                )

                for item in items
            )


            if matched:

                negative_points += weight


    # ========================================================
    # NO LEARNED SIGNALS
    # ========================================================

    if maximum_points == 0:

        return 50.0


    # ========================================================
    # CONVERT TO 0-100
    # ========================================================

    raw_score = (

        positive_points

        -

        negative_points
    )


    normalized_score = (

        (
            raw_score
            +
            maximum_points
        )

        /

        (
            2
            *
            maximum_points
        )

    ) * 100


    return round(

        max(
            0,
            min(
                normalized_score,
                100
            )
        ),

        2
    )